### ISSUE TITLE
Playlist support

### ISSUE THREAD

**Issue by DmitryEfimenko** [kanzelm3/angular-video-bg#4]
Awesome project!
I know that dynamic change of videos is in Potential Features, but I wanted to throw in an idea regarding one way of implementing this:
Directive could accept an array of objects where each object would describe a video (url, start time, end time... whatever other suitable options) - and play them in specified (or random) sequence.

**Comment by kanzelm3** [comment]
I like the idea of implementing a "playlist" feature, maybe have a new option on the directive for playlist that expects an array of video objects like you mentioned. You still set up the default options on the directive, and then you can override them or add new options on a video by video basis in the video objects in the playlist. What do you think about that @DmitryEfimenko?

**Comment by DmitryEfimenko** [comment]
Sounds great! The only thing that comes to mind is that if the options for the array of videos are going to be exactly the same as for one video, it might make sense to store them in the array by default.

**Comment by kanzelm3** [comment]
Well, what I'm thinking is that I will keep all of the options as is, along with video-id attribute; that way for the most common and simple use-case, it remains a simple interface. 

What I will then do is add a new playlist attribute (or maybe call it videos), and that attribute will accept an array of videos. The object for each video would have all of the same options as the main directive, and the directive would throw an error if you had a video-id attribute AND a playlist attribute (since you could only have one or the other). 

Each of the videos in the playlist array would pull their options from the default options set on the directive, unless you specifically set a different option on one (or more) of the videos. This would be a much better interface because that way you don't have to have a bunch of repetitive options on each of the videos in the playlist (you could still do it that way if you wanted, because all of the options on the directive are optional).

I think this would be the best way forward and I will get to work on this feature before I start on any of the others, let me know if you disagree or if you have any further feedback @DmitryEfimenko

**Comment by DmitryEfimenko** [comment]
No, actually this sounds very reasonable. Good thought process!

**Comment by kanzelm3** [comment]
@DmitryEfimenko this has been implemented in the latest release. Let me know if you find any bugs!

**Comment by DmitryEfimenko** [comment]
wow, you are quick!
