### ISSUE TITLE
Not displaying video

### ISSUE THREAD

**Issue by W0lfbane** [kanzelm3/angular-video-bg#9]
Hi there! I'm a bit new to Angular, so I might be making a stupid mistake. I've currently setup my Angular app as instructed and am using a valid video ID, however it doesn't seem to be displaying any video. 

If it matters, I am using Rails has the backend for my web application. I'm not sure what to include to help troubleshoot the issue, but am happy to reply with whatever is requested.

**Comment by kanzelm3** [comment]
I can't really help you debug this unless you give me some code to look at. Are you injecting 'angularVideoBg' as a dependency into your angular module? Are you trying to put the video ID directly into the directive, and not using a variable from your controller? If that's the case you need to put your video ID in quotes like so:

``` html
<video-bg video-id="'sLprVF6d7Ug'"></video-bg>
<!-- note the single quotes around the video ID -->
```

**Comment by kanzelm3** [comment]
@DrakkenSaer were you able to figure it out?

**Comment by W0lfbane** [comment]
Not yet. Sorry for the delay.

This is my app.js (the module wrapping my application):

```
(function() {
  app = angular.module('app', ['templates', 'ngRoute', 'angularVideoBg']);

  app.config([
    '$httpProvider', function($httpProvider) {
      return $httpProvider.defaults.headers.common['X-CSRF-Token'] = $('meta[name=csrf-token]').attr('content');
    }
  ]);

  app.config([
    '$routeProvider', function($routeProvider) {
      return $routeProvider
        .when('/', {
        templateUrl: "pages/home.html",
        title: "Home",
        controller: "HomeCtrl"
      })
        .when('/about', {
        templateUrl: "pages/about.html",
        title: "About me"
      })


        .otherwise({

      });
    }
  ]);

  app.run(function() {
    return console.log('angular app running');
  });

  app.controller('TestCtrl', ['$scope', function($scope) {
    $scope.test = "Angular load: Successful";
  }]);
})();
```

I'm using this in my Home template: 

```
<video-bg video-id="'e-ORhEE9VVg'">
```

I've required the JS file so that the rail's asset pipeline picks it up, and verified that it is actually being included in the page too.

**Comment by kanzelm3** [comment]
Do you have a div or something wrapping it that has ng-controller="TestCtrl" on it? 

Do you have ng-app="app" on your body or html or something? 

I don't see a closing tag on the video-bg element. What content do you want the video to be the background of? 

I'd like to see some more of your markup so that I can help you troubleshoot what's wrong. Are you getting any console errors or messages?

**Comment by W0lfbane** [comment]
Yes, it's wrapped in the footer partial I have: 

```
<div class="container-fluid <%= 'white' if current_page?(root_path) %>">
  <div class="container">
    <footer class="navbar navbar-static-bottom">
      <nav>
        <ul class="nav navbar-nav">
          <li><%= link_to image_tag("facebook.png"), "https://facebook.com/DemonFromHeaven" %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'Source code', 'https://github.com/drakkensaer/portfolio' %></li>
          <li><%= link_to 'GitHub', 'https://github.com/drakkensaer' %></li>
          <li><%= link_to 'Resume', resume_index_path, target: '_blank' %></li>
          <% if signed_in? %>
          <li><%= link_to 'Messages', messages_path %></li>
          <li><%= link_to 'Logout', logout_path, method: :delete %></li>
          <% end %>  
        </ul>
      </nav>
      <%= debug(params) if Rails.env.development? %>
      <div ng-controller="TestCtrl" class="debug_dump">{{test}}</div>
    </footer>  
  </div>
</div>
```

Ng-app is included with my HTML tag: 

```
<!DOCTYPE html>
<html ng-app="app" ng-strict-di>
  <head>
    <title ng-bind="'Saer Designs | ' + title">Saer Designs</title>
    <%= stylesheet_link_tag  'application' %>
    <%= stylesheet_link_tag  'http://fonts.googleapis.com/css?family=Berkshire+Swash' %>
    <%= stylesheet_link_tag  'http://fonts.googleapis.com/css?family=Abel' %>
    <%= stylesheet_link_tag  'http://fonts.googleapis.com/css?family=Oregano' %>
    <%= javascript_include_tag 'application', controller_name %>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= csrf_meta_tags %>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords" content="web developer, web design, ruby on rails, css, bootstrap, jquery, website builder, ruby, php">
    <meta name="author" content="Drakken Saer">
    <meta name="robots" content="index, follow">
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <!-- do not render on resume page -->
    <div ng-include="'layouts/header.html'"></div>
    <!-- conditional container logic used for CSS needs for specific pages -->
    <div ng-view id="main">

      <!-- for page flash alerts -->
      <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %> alert-dismissible container" role="alert">
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span   class="sr-only">Close</span></button>
        <%= value %>
      </div>
      <% end %>

      <!-- page content goes here -->
      <%= yield %>

    </div>
    <!-- do not render on resume page -->
    <%= render "layouts/footer" unless current_page?(resume_index_path) %>
  </body>

  <!-- for page-specific CSS or JS -->
  <%= yield :page_script %>

</html>
```

Whoops! I did forget to put a closing, I accidentally left it out when I was trying to figure out what was wrong. Including it again hasn't seem to fix it though. 

I'd forgotten to check earlier, but there is an error in the console which only occurs when I've got the video-bg directive on the page: 

```
Navigation Event Separator
HTML1300: Navigation occurred.
ruby-on-rails-112667.nitrousapp.com:3000
angular app running
app.js (36,5)
Error: [$injector:strictdi] function($window, $q, $timeout) is not using explicit annotation and cannot be invoked in strict mode
http://errors.angularjs.org/1.4.3/$injector/strictdi?p0=function(%24window%2C%20%24q%2C%20%24timeout)
   at annotate (http://ruby-on-rails-112667.nitrousapp.com:3000/assets/angular.js?body=1:3721:11)
   at invoke (http://ruby-on-rails-112667.nitrousapp.com:3000/assets/angular.js?body=1:4429:11)
   at Anonymous function (http://ruby-on-rails-112667.nitrousapp.com:3000/assets/angular.js?body=1:6942:17)
   at forEach (http://ruby-on-rails-112667.nitrousapp.com:3000/assets/angular.js?body=1:337:11)
   at Anonymous function (http://ruby-on-rails-112667.nitrousapp.com:3000/assets/angular.js?body=1:6940:13)
   at invoke (http://ruby-on-rails-112667.nitrousapp.com:3000/assets/angular.js?body=1:4451:7)
   at enforcedReturnValue (http://ruby-on-rails-112667.nitrousapp.com:3000/assets/angular.js?body=1:4304:7)
   at invoke (http://ruby-on-rails-112667.nitrousapp.com:3000/assets/angular.js?bod
angular.js (12331,11)
SEC7115: :visited and :link styles can only differ by color. Some styles were not applied to :visited.
ruby-on-rails-112667.nitrousapp.com:3000
```

**Comment by W0lfbane** [comment]
So the issue seems to be with the strict dependency injection. After reading the console error, I decided to remove it. The video is now working.

**Comment by kanzelm3** [comment]
What version of angular-video-bg are you using?

**Comment by W0lfbane** [comment]
I'm using version 0.3.0

**Comment by benjaminboruff** [comment]
```
Error: [$injector:strictdi] function($window, $q, $timeout) is not using explicit annotation and cannot be invoked in strict mode

```

That's exactly where I removed the explicit injection, and put the injection above via:

```
videoBg.$inject = ['$window', '$q', '$timeout'];

```

but I just added the ng-strict-di attribute (strict mode) to my html file and had no errors at all. I'm using angular 1.4.0, looks like this is using 1.4.3? Weird. You might try adding the ngAnnotate back into the build task to see if that has something to do with it. It doesn't hurt to use it with the separate injector. I'll give 1.4.3 a try without ngAnnotate to see what happens.

**Comment by benjaminboruff** [comment]
Upgraded my site to angular 1.4.3, rebuilt (reconcat/reminify) with  ng-strict-di in my index.html, no ngAnnotate, still no problems/errors at all. 

I'm not a rails person ... I would suggest making a basic html/angular site/app sans rails, and see if the issue persists.

**Comment by benjaminboruff** [comment]
I don't know if this has anything to do with the problem, but I looked at the min.js file and noticed that videoBg.$inject = ['$window', '$q', '$timeout']; is the very last expression in the file. What file is being used in the project: angular-video-bg.js or the angular-video-bg.min.js file?

I'm beginning to suspect that this issue is caused by the use of a non-minified angular-video-bg.js file (that's why removing the ng-strict-di attribute stops the errors/"fixes" the poblem), that does not have the videoBg.$inject = ['$window', '$q', '$timeout']; expression  in the file. Older file than current perhaps? Can we see the angular-video-bg.js and min.js files being used? 

I also checked and indeed, the angularjs-rails repo is using 1.4.3 (but I doubt that's an issue).

**Comment by benjaminboruff** [comment]
Indeed! I just reproduced the error!

```
Error: [$injector:strictdi] videoBg is not using explicit annotation and cannot be invoked in strict mode
http://errors.angularjs.org/1.4.2/$injector/strictdi?p0=videoBg
    at REGEX_STRING_REGEXP (angular.js:68)
    at Function.annotate (angular.js:3722)
    at Object.invoke (angular.js:4430)
    at angular.js:6943
    at forEach (angular.js:336)
    at Object.<anonymous> (angular.js:6941)
    at Object.invoke (angular.js:4452)
    at Object.enforcedReturnValue [as $get] (angular.js:4305)
    at Object.invoke (angular.js:4452)
    at angular.js:4270

```

I commented out the videoBg.$inject = ['$window', '$q', '$timeout']; expression from the non-minified version (angular-video-bg.js), using the ng-strict-di attribute in the index.html file, and KABOOM! 

The ng-strict-di attribute is used for testing whether a non-minified file is minification-safe. Without using ngAnnotate, or adding the videoBg.$inject = ['$window', '$q', '$timeout']; to the angular-video-bg.js file (which is the way the current file is), then yes, it will crash if you use the ng-strict-di attribute. So you can either use ngAnnotate in your build task, or use the current files from the repo on github (both the current js and min.js files are good).

The error from the original issue

```
 function($window, $q, $timeout) is not using explicit annotation ...
```

rather than the error I reproduced

```
videoBg is not using explicit annotation ...

```

makes me think the function was possibly copied/pasted from below the $inject line if the source was the current version. If not, then it must be a from a file obtained before the current version.

PS - you don't need to use the ng-strict-di attribute if you are using a minified file(s); because minified files will crash no matter what if they are made without using ngAnnotate, from source files that were not crafted as minification safe to begin with (using function_name.$inject = [ "stuff", "other_stuff", etc];). I hope that makes sense.

**Comment by kanzelm3** [comment]
Thanks for your help in debugging this @benjaminboruff! I am going to go ahead and close this issue.

**Comment by W0lfbane** [comment]
After reviewing the JS file that bower downloaded, and the one on here, there seems to be a mismatch. Oddly enough bower doesn't seem to be downloading the most current version of the files on the repo. I'll have to troubleshoot bower on my own, but thanks for helping me find out the problem guys!

**Comment by kanzelm3** [comment]
@DrakkenSaer you were correct, the latest commits that added the explicit annotation were not in the 0.3.0 release. I have added a new release, 0.3.1, that contains them so if you update to v0.3.1 it should work for you now. If you have it in bower as "~0.3" and you do `bower update angular-video-bg` then it should update you to v0.3.1.
